name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python v3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install hatch
        run: |
          pip install hatch

      - name: Run tests
        run: |
          hatch run test:test
